all:
	gcc  -Wall -O2 -g  -I.  ionapp_import.c ipcsocket.c ionutils.c   -o ionapp_import
	gcc  -Wall -O2 -g  -I. ionapp_export.c ipcsocket.c ionutils.c   -o ionapp_export

clean:
	rm ionapp_import
	rm ionapp_export
