###
# scripts contains sources for various helper programs used throughout
# the kernel for the build process.
# ---------------------------------------------------------------------------

always		:= $(hostprogs-y)

# Let clean descend into subdirs
subdir-	+= basic kconfig
